### PR TITLE
feat: add shimmer effect on about us view

### PR DESCRIPTION
**Pull request by kamilfedio**
#205 
I think is better way to write some shimmer boxes than using the same ui style us in guide view for user experience. If u think differently I can change it ofc

### CODE REVIEW

**Comment by mikolaj-jalocha** [comment]
> #205 I think is better way to write some shimmer boxes than using the same ui style us in guide view for user experience. If u think differently I can change it ofc

Could you please attach some screenshots?

**Comment by kamilfedio** [comment]
@mikolaj-jalocha yup
image

**Review by simon-the-shark — APPROVED** [review]
Good job!

My previous suggestion about using guide view was just a thing to make this task quicker - but customized view is even better. So good job here. It looks fire 🔥 

The code is fine as well - my only note is that you could have made your work a bit easier using our ready to use helpers like `PreviewCardLoading` or `ScrollableLoaderBuilder` in few places. But it's not a problem for me, it's just a loading view so your build is actually maybe even a bit more performant like this and it looks fine too. So if you want you can check if you can use `PreviewCardLoading` or `ScrollableLoaderBuilder` or smth here, but we can also just merge it honestly. So you can try to refactor if you want or we're merging it - whatever you prefer - just let me know. I do give merge approval here even with the current state of things

**Comment by kamilfedio** [comment]
Okay I will try to refactor tommorow

**Comment by kamilfedio** [comment]
@simon-the-shark  okay little delay but i refactor. Only im not sure aboutmy correct use of `ScrollableLoaderBuilder`

**Review by simon-the-shark — APPROVED** [review]
Great, You've used it correctly. My only note is that these widgets are self sufficient and you do not any extra Shimmer or ShimmerLoadingItem above it

**Pull request merged**
