### PR TITLE
Feat/ add remote cache flushing

### PR DESCRIPTION
**Pull request by simon-the-shark**
we check remote number on directus and if it increased, we flush all cache

tell me what you think

### CODE REVIEW

**Review by mikolaj-jalocha — APPROVED** [review]
LGTM! 

I've one question. In Android native development I'd probably use one of the lifecycle 's method. What about [them ](https://yawarosman.medium.com/flutter-lifecycle-methods-an-in-depth-exploration-00b0747864bb)here?

**Comment by simon-the-shark** [comment]
@mikolaj-jalocha  Do you want to use **app's** lifecycle method? Cause I already used `initState` which is **widget's** lifecycle method and it will be triggered only on first appereance of the widget in the tree, which in this cause (taking into account its position in the tree) - means it makes the request only once, after opening the app. You need to close the app and reenter to retrigger the request. So do you think we should  check this also when we get back to the app from the background or what's your specific proposition?

**Comment by mikolaj-jalocha** [comment]
> @mikolaj-jalocha Do you want to use **app's** lifecycle method? Cause I already used `initState` which is **widget's** lifecycle method and it will be triggered only on first appereance of the widget in the tree, which in this case (taking into account its position in the tree) - means it makes the request only once, after opening the app. You need to close the app and reenter to retrigger the request. So do you think we should check this also when we get back to the app from the background or what's your specific proposition?

No no, everything here works as expected. I was wondering if  we could  use only lifecycle methods and ommit creating separate widget. Just curious 🤔

**Comment by simon-the-shark** [comment]
We can use `WidgetsBindingObserver`, but it's a mixin for a widget (so we need widget) or we can use `AppLifecycleListener` class, which is a separate class (nice to use) - but we still need to attach it to the app (and we need to do that in some widget :P) - so we do need widget. If we use hooks, this can be simplified (less boilerplate)

**Pull request merged**
