### PR TITLE
fix/map-rotating-when-zooming

### PR DESCRIPTION
**Pull request by tomasz-trela**

### CODE REVIEW

**Comment by mikolaj-jalocha** [comment]
Solution looks good to me! Please fix linter complaints ;)

**Comment by tomasz-trela** [comment]
> Solution looks good to me! Please fix linter complaints ;)

image
I've done everything from this ss. I think it is linter issue

**Comment by simon-the-shark** [comment]
yeah, you're right - gh workflow broke for some reason

**Comment by simon-the-shark** [comment]
I'll fix it later

**Pull request merged**
