### PR TITLE
Feat/add tap detection on whole big preview card (and splash)

### PR DESCRIPTION
**Pull request by tomasz-trela**
Idk why splash doesn't work in my code. Tile splash with stack widget don't work aswell. (In first option gesture detector works properly) #456

### CODE REVIEW

**Comment by tomasz-trela** [comment]
Just now I've tried and I'm giving up for now. Tomorrow I will try again.

**Comment by simon-the-shark** [comment]
@tomasz-trela You probably need to dive into BigPreviewCard code and add it there.

**Comment by simon-the-shark** [comment]
You can add it in general for the BigPreviewCard

**Comment by tomasz-trela** [comment]
Tile splash fixed. This article help me with this issue.
https://therdm.medium.com/ripple-effect-not-working-on-inkwell-try-the-ink-widget-44b6a1964de0

**Review by mikolaj-jalocha — APPROVED** [review]
LGTM! Consider adding link to the article with the solution (as a comment in code)

**Review by mikolaj-jalocha — APPROVED** [review]

**Pull request merged**
